include: package:flutter_lints/flutter.yaml

linter:
  rules:

    prefer_single_quotes: true
    always_use_package_imports: true
    annotate_overrides: true
    require_trailing_commas: true
    prefer_mixin: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_fields: true
    always_put_required_named_parameters_first: true
    file_names: true