name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  analyze:
    name: Analyze app
    runs-on: platform
    steps: 
      - run: flutter pub get
      - run: dart analyze --no-fatal-infos
      - run: dart format lib --set-exit-if-changed .
  test:
    runs-on: platform
    steps:
      - run: flutter test
