name: Dart

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    
jobs:
  analyze:
    name: Analyze ${{ matrix.target }} app
    runs-on: ${{ matrix.os }}
    steps: 
      - run: flutter pub get
      - run: dart analyze --no-fatal-infos
      - run: dart format lib --set-exit-if-changed .
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - run: flutter test
